### ISSUE TITLE
تغییر تاریخ پیکر در فرم ویرایش داده

### ISSUE THREAD

**Issue by dev-alireza** [Saeed-Pooyanfar/ng-persian-datepicker#46]
با سلام و خسته نباشید.
من می خواهم از این پیکر در یک فرم ویرایش داده استفاده کنم و نیاز دارم تا مقداری که از Web API خواند میشه به پیکر نیز اعمال شود من از روش Reactive Forms فرم استفاده میکنم و input را به Form Control مربوط وصل می کنم . مقدار تاریخ درون input به درستی قرار می گیرد ولی زمانی که پیکر را باز می کنم تاریخ امروز را نشان می دهد اگر کسی از دوستان راه حلی برای این مشکل دارد لطفا راهنمایی کند

**Comment by Saeed-Pooyanfar** [comment]
Hi,
That's because `ng-persian-datepicker` currently doesn't support `FormControl` or `ngModel`
Yes! I know that's a weak point for an angular package!
I should add ReactiveForm support in v4.x.x
For now:
You can use it as i implement it in demo component:
https://github.com/Saeed-Pooyanfar/ng-persian-datepicker/tree/master/src/app/demo

**Comment by dev-alireza** [comment]
با سلام و خسته نباشید.
با تشکر از  جواب و راهنمایتون. من از این روش استفاده کردم ولی به دلیل اینکه داده ها از Web API به صورت Async  میاد و بعد از ساخته شدن View داده ها آماده میشه از این روش نمیشه استفاده کرد این روش فقط در صورتی که تاریخ یک مقدار ثابت باشه و نخواهیم از Web API مقادیر را دریافت کنیم به درستی عمل میکنه و در پروژه ای که من در حال کارکردن روی آن هستم یک تعداد زیادی فرم ویرایش داده داریم که در هر کدام چند Date Picker وجود دارد آیا امکان اضافه کردن این قابلیت (Reactive Forms)  به سورس ng-persian-datepicker به وسیله خودم هست؟
با تشکر.

**Comment by Saeed-Pooyanfar** [comment]
You can wait for dateValue:

```typescript
dateValue: number | undefined;

onResponse(data: any): void {
  this.dateValue = data.dateValue;
}
```

```html
<ng-container *ngIf="dateValue">
  <ng-persian-datepicker [dateValue]="dateValue"></ng-persian-datepicker>
</ng-container>
```

**Comment by Saeed-Pooyanfar** [comment]
@dev-alireza please check v4.0.0
I just add support for ReactiveForm
Thanks!

**Comment by hedyehloo** [comment]
Hello Saeed.
what if we don't have any ReactiveForm?!
and now [dateValue] and [input] are not available

**Comment by Saeed-Pooyanfar** [comment]
@hedyehloo 
Hi
You can set date value by using `formControlName` inside a `formGroup`
This is a breaking change feature and that's why i jumped to v4.x.x
`ReactiveFormsModule` is a standard tool in `@angular/forms`
So try it. (It's recommend way to dealing with forms by angular team).  

For installation:
Probably you should upgrade `rxjs` to `^7.4`

**Comment by hedyehloo** [comment]
Hi,
dateInitValue not work in v4 and dateValue in reactive form is always a string persian date.
how to get Gregorian value?!

**Comment by Saeed-Pooyanfar** [comment]
@hedyehloo 
You can use `(dateOnInit)` `$event: IActiveDate`
